### ISSUE TITLE
Find out how to create binaries for electron app

### ISSUE THREAD

**Issue by danielbulgakov** [danielbulgakov/ecg_esp32#3]

**Comment by DDYunin** [comment]
@danielbulgakov, And do i need to make pull request for this feature or we make it on Friday?

**Comment by danielbulgakov** [comment]
You can open PRs any time you want.
If don't have merge problems, can merge yourself

**Comment by DDYunin** [comment]
OK, i had this question because i thought that this functional you would use right now. If it's true (you don't use this functional now), let's add PR on current Friday
